/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLCoffeeShop;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HIEU
 */
public class QuanLySanPham extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
    List<ThucAn> dsta = new ArrayList<>();
    List<NuocUong> dsnu = new ArrayList<>();
    
 
    /**
     * Creates new form QuanLySanPham
     * @throws java.sql.SQLException
     */
    public QuanLySanPham() throws SQLException {
        initComponents();
        //Thiết lập Background color
        this.getContentPane().setBackground(Color.WHITE);

        showTA();
        showNU();
    }
    
   
    //Hiển thị danh sách thức ăn ban đầu
    public void showTA() throws SQLException {
        tableModel = (DefaultTableModel) tbthucan.getModel();
        dsta = QLThucAn.findALLTA();
        
        tableModel.setRowCount(0); //Dữ liệu bắt đầu hiển thị từ hàng đầu tiên
        //Nếu không thì sẽ hiện thị từ hàng thứ 5
        dsta.forEach(ta -> {
            tableModel.addRow(new Object[]{
                ta.getMaSP(),
                ta.getTenSP(),
                ta.getGiaBan(),
                ta.getTinhTrang(),
                ta.getThoiDiemBan(),
                ta.getDanhMuc(),
                ta.getLoaiTA()
            });
        });
    }
    //Hiển thị danh sách nước uống ban đầu
    public void showNU() throws SQLException{
        tableModel = (DefaultTableModel) tbnuocuong.getModel();
        dsnu = QLNuocUong.findAllNU();
        
        tableModel.setRowCount(0); //Dữ liệu bắt đầu hiển thị từ hàng đầu tiên
        //Nếu không thì sẽ hiện thị từ hàng thứ 5
        dsnu.forEach(tu -> {
            tableModel.addRow(new Object[] {
                tu.getMaSP(),
                tu.getTenSP(),
                tu.getGiaBan(),
                tu.getTinhTrang(),
                tu.getThoiDiemBan(),
                tu.getDanhMuc(),
                tu.getLoaiNU()
            });
        });
    }
    //Hiển thị danh sách thức ăn đã được sắp xếp theo giá
    public void showDanhSachTASapXep() throws SQLException {
        tableModel = (DefaultTableModel) tbthucan.getModel();
        dsta = QLThucAn.sapXepThucAnTheoGia();

        tableModel.setRowCount(0); //Dữ liệu bắt đầu hiển thị từ hàng đầu tiên
        //Nếu không thì sẽ hiện thị từ hàng thứ 5
        dsta.forEach(ta -> {
            tableModel.addRow(new Object[]{
                ta.getMaSP(),
                ta.getTenSP(),
                ta.getGiaBan(),
                ta.getTinhTrang(),
                ta.getThoiDiemBan(),
                ta.getDanhMuc(),
                ta.getLoaiTA()
            });
        });
    }
    //Hiển thị danh sách thức ăn đã được sắp xếp theo giá
    public void showDanhSachNUSapXep() throws SQLException {
        tableModel = (DefaultTableModel) tbnuocuong.getModel();
        dsnu = QLNuocUong.sapXepNuocUongTheoGia();

        tableModel.setRowCount(0); //Dữ liệu bắt đầu hiển thị từ hàng đầu tiên
        //Nếu không thì sẽ hiện thị từ hàng thứ 5
        dsnu.forEach(nu -> {
            tableModel.addRow(new Object[]{
                nu.getMaSP(),
                nu.getTenSP(),
                nu.getGiaBan(),
                nu.getTinhTrang(),
                nu.getThoiDiemBan(),
                nu.getDanhMuc(),
                nu.getLoaiNU()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbthucan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbnuocuong = new javax.swing.JTable();
        btnthemta = new javax.swing.JButton();
        btntimkiemta = new javax.swing.JButton();
        btnxoata = new javax.swing.JButton();
        btnsxta = new javax.swing.JButton();
        btnthemnu = new javax.swing.JButton();
        btntimkiemnu = new javax.swing.JButton();
        btnxoanu = new javax.swing.JButton();
        btnsapxepnutheogia = new javax.swing.JButton();
        btntimkiemtatheogia = new javax.swing.JButton();
        btntimkiemnutheogia = new javax.swing.JButton();
        btnchonTA = new javax.swing.JButton();
        btnchonNU = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnQuayVe = new javax.swing.JButton();
        btnHienThiNuocUong = new javax.swing.JButton();
        btnHienThiMonAn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SẢN PHẨM");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DANH MỤC MÓN ĂN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DANH MỤC NƯỚC UỐNG");

        tbthucan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thức Ăn", "Tên Thức Ăn", "Giá Bán", "Tình Trạng", "Thời Điểm Bán", "Danh Mục ", "Loại Thức Ăn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbthucan);

        tbnuocuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nước Uống", "Tên Nước Uống", "Giá Bán", "Tình Trạng", "Thời Điểm Bán", "Danh Mục", "Loại Thức Uống"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbnuocuong);

        btnthemta.setBackground(new java.awt.Color(255, 255, 255));
        btnthemta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthemta.setText("Thêm Thức Ăn");
        btnthemta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthemta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemtaActionPerformed(evt);
            }
        });

        btntimkiemta.setBackground(new java.awt.Color(255, 255, 255));
        btntimkiemta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemta.setText("Tìm Kiếm Theo Tên");
        btntimkiemta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntimkiemta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemtaActionPerformed(evt);
            }
        });

        btnxoata.setBackground(new java.awt.Color(255, 255, 255));
        btnxoata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoata.setText("Xóa Món Ăn");
        btnxoata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoataActionPerformed(evt);
            }
        });

        btnsxta.setBackground(new java.awt.Color(255, 255, 255));
        btnsxta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsxta.setText("Sắp Xếp Theo Giá");
        btnsxta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsxta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsxtaActionPerformed(evt);
            }
        });

        btnthemnu.setBackground(new java.awt.Color(255, 255, 255));
        btnthemnu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthemnu.setText("Thêm Nước Uống");
        btnthemnu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthemnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemnuActionPerformed(evt);
            }
        });

        btntimkiemnu.setBackground(new java.awt.Color(255, 255, 255));
        btntimkiemnu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemnu.setText("Tìm Kiếm Theo Tên");
        btntimkiemnu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntimkiemnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemnuActionPerformed(evt);
            }
        });

        btnxoanu.setBackground(new java.awt.Color(255, 255, 255));
        btnxoanu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoanu.setText("Xóa Nước Uống");
        btnxoanu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanuActionPerformed(evt);
            }
        });

        btnsapxepnutheogia.setBackground(new java.awt.Color(255, 255, 255));
        btnsapxepnutheogia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsapxepnutheogia.setText("Sắp Xếp Theo Giá");
        btnsapxepnutheogia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsapxepnutheogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapxepnutheogiaActionPerformed(evt);
            }
        });

        btntimkiemtatheogia.setBackground(new java.awt.Color(255, 255, 255));
        btntimkiemtatheogia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemtatheogia.setText("Tìm Kiếm Theo Giá");
        btntimkiemtatheogia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntimkiemtatheogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemtatheogiaActionPerformed(evt);
            }
        });

        btntimkiemnutheogia.setBackground(new java.awt.Color(255, 255, 255));
        btntimkiemnutheogia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemnutheogia.setText("Tìm Kiếm Theo Giá");
        btntimkiemnutheogia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntimkiemnutheogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemnutheogiaActionPerformed(evt);
            }
        });

        btnchonTA.setBackground(new java.awt.Color(255, 255, 255));
        btnchonTA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnchonTA.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\outline_task_alt_black_24.png")); // NOI18N
        btnchonTA.setText("Chọn Thức Ăn");
        btnchonTA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnchonTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonTAActionPerformed(evt);
            }
        });

        btnchonNU.setBackground(new java.awt.Color(255, 255, 255));
        btnchonNU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnchonNU.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\outline_task_alt_black_24.png")); // NOI18N
        btnchonNU.setText("Chọn Nước Uống");
        btnchonNU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnchonNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonNUActionPerformed(evt);
            }
        });

        btnQuayVe.setBackground(new java.awt.Color(255, 255, 255));
        btnQuayVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuayVe.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\outline_logout_black_24.png")); // NOI18N
        btnQuayVe.setText("Màn Hình Chính");
        btnQuayVe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayVeActionPerformed(evt);
            }
        });

        btnHienThiNuocUong.setBackground(new java.awt.Color(255, 255, 255));
        btnHienThiNuocUong.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\baseline_refresh_black_18.png")); // NOI18N
        btnHienThiNuocUong.setBorder(null);
        btnHienThiNuocUong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiNuocUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiNuocUongActionPerformed(evt);
            }
        });

        btnHienThiMonAn.setBackground(new java.awt.Color(255, 255, 255));
        btnHienThiMonAn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\baseline_refresh_black_18.png")); // NOI18N
        btnHienThiMonAn.setBorder(null);
        btnHienThiMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiMonAnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntimkiemta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsxta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btntimkiemtatheogia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(btnxoata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnQuayVe))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHienThiNuocUong, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHienThiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnthemnu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntimkiemnu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btntimkiemnutheogia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnsapxepnutheogia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnxoanu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnchonNU, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnthemta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnchonTA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHienThiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnxoata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthemta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsxta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnchonTA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntimkiemta)
                    .addComponent(btntimkiemtatheogia))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthemnu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnxoanu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnchonNU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsapxepnutheogia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntimkiemnutheogia)
                            .addComponent(btntimkiemnu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(btnQuayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHienThiNuocUong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Button thêm thức ăn (chạy)
    private void btnthemtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemtaActionPerformed
        try {
            int inputMaTA = Integer.parseInt(JOptionPane.showInputDialog(this, 
                "Nhập mã thức ăn"));
            String inputTenTA = JOptionPane.showInputDialog(this, "Nhập tên thức ăn");
            double inputGiaBan = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Nhập giá bán"));
            String inputTinhTrang = JOptionPane.showInputDialog(this, "Nhập tình trạng");
            String inputThoiDiemBan = JOptionPane.showInputDialog(this, "Nhập thời điểm bán");
            String inputDanhMucSP = JOptionPane.showInputDialog(this, "Nhập danh mục sản phẩm");
            String inputLoaiTA = JOptionPane.showInputDialog(this, "Nhập loại thức ăn");
            
            //Chọn phương thức khởi tạo không ID vì ID là khóa chính của bảng
            ThucAn ta = new ThucAn(inputMaTA,inputTenTA, inputGiaBan, inputTinhTrang, 
                    inputThoiDiemBan, inputDanhMucSP, inputLoaiTA);
            
            QLThucAn.themTA(ta);
            showTA();

        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthemtaActionPerformed
    //Buttton xóa thức ăn (Chạy)
    private void btnxoataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoataActionPerformed
        //Xóa cả ở CSDL
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbthucan.getSelectedRow();
        if (selectedIndex >= 0) { //Đúng
            ThucAn ta = dsta.get(selectedIndex);
            //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa món ăn này?");
            System.out.println("option: " + option);  
            //Ouput => Yes: 0, No: 1, Cancel: 2
            if (option == 0) {
                try {
                    QLThucAn.xoaTA(ta.getTenSP());//Xóa Bàn
                    showTA(); //Hiện thị danh sách nhân viên sau khi xóa
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnxoataActionPerformed
    //Buttton xóa nước uống (Chạy)
    private void btnxoanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanuActionPerformed
        //Xóa cả ở CSDL
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbnuocuong.getSelectedRow();
        if (selectedIndex >= 0) { //Đúng
            NuocUong nu = dsnu.get(selectedIndex);
            //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa thức uống này?");
            System.out.println("option: " + option);
            //Ouput => Yes: 0, No: 1, Cancel: 2
            if (option == 0) {
                try {
                    QLNuocUong.xoaNU(nu.getTenSP());//Xóa Bàn
                    showNU(); //Hiện thị danh sách nhân viên sau khi xóa
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnxoanuActionPerformed
    //Button thêm nước uống (chạy)
    private void btnthemnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemnuActionPerformed
        try {
            int inputMANU = Integer.parseInt(JOptionPane.showInputDialog(this, 
                "Nhập mã Nước Uống"));
            String inputTenNU = JOptionPane.showInputDialog(this, "Nhập tên nước uống");
            double inputGiaBan = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Nhập giá bán"));
            String inputTinhTrang = JOptionPane.showInputDialog(this, "Nhập tình trạng");
            String inputThoiDiemBan = JOptionPane.showInputDialog(this, "Nhập thời điểm bán");
            String inputDanhMucSP = JOptionPane.showInputDialog(this, "Nhập danh mục sản phẩm");
            String inputLoaiNU = JOptionPane.showInputDialog(this, "Nhập loại nước uống");
            
            //Chọn phương thức khởi tạo không ID vì ID là khóa chính của bảng
            NuocUong nu = new NuocUong(inputMANU, inputTenNU, inputGiaBan, inputTinhTrang,
                    inputThoiDiemBan, inputDanhMucSP, inputLoaiNU);
            
            QLNuocUong.themNU(nu);
            showNU();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthemnuActionPerformed
    //Button tìm kiếm thức ăn theo tên
    private void btntimkiemtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemtaActionPerformed
        String inputTenTA = JOptionPane.showInputDialog(this, "Nhập tên thức ăn cần tìm");

        if (inputTenTA.length() > 0) {
            try {
                dsta = QLThucAn.timKiemTA(inputTenTA);
                
                tableModel = (DefaultTableModel) tbthucan.getModel();
                
                tableModel.setRowCount(0);
                
                dsta.forEach(ta -> {
                    tableModel.addRow(new Object[]{
                        ta.getMaSP(),
                        ta.getTenSP(),
                        ta.getGiaBan(),
                        ta.getTinhTrang(),
                        ta.getThoiDiemBan(),
                        ta.getDanhMuc(),
                        ta.getLoaiTA()
                    });
                });
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btntimkiemtaActionPerformed
    //Button tìm kiếm nước uống theo tên (Chạy)
    private void btntimkiemnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemnuActionPerformed
        String inputTenNU = JOptionPane.showInputDialog(this, "Nhập tên nước uống cần tìm");

        if (inputTenNU.length() > 0) {
            try {
                dsnu = QLNuocUong.timKiemNU(inputTenNU);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            tableModel = (DefaultTableModel) tbnuocuong.getModel();

            tableModel.setRowCount(0);

            dsnu.forEach(nu -> {
                tableModel.addRow(new Object[]{
                    nu.getMaSP(),
                    nu.getTenSP(),
                    nu.getGiaBan(),
                    nu.getTinhTrang(),
                    nu.getThoiDiemBan(),
                    nu.getDanhMuc(),
                    nu.getLoaiNU()
                });
            });
        }
    }//GEN-LAST:event_btntimkiemnuActionPerformed
    //Button tìm kiếm thức ăn theo khoảng giá (Chạy)
    private void btntimkiemtatheogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemtatheogiaActionPerformed
        double inputTuGia = Integer.parseInt(JOptionPane.showInputDialog(this,
                "Từ"));
        double inputDenGia = Integer.parseInt(JOptionPane.showInputDialog(this,
                "Đến"));

        if (inputTuGia > 0 && inputDenGia > 0) {
            try {
                dsta = QLThucAn.timKiemTA(inputTuGia, inputDenGia);
                
                tableModel = (DefaultTableModel) tbthucan.getModel();

                tableModel.setRowCount(0);

                dsta.forEach(ta -> {
                    tableModel.addRow(new Object[]{
                        ta.getMaSP(),
                        ta.getTenSP(),
                        ta.getGiaBan(),
                        ta.getTinhTrang(),
                        ta.getThoiDiemBan(),
                        ta.getDanhMuc(),
                        ta.getLoaiTA()
                    });
                });
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btntimkiemtatheogiaActionPerformed
    //Button tìm kiếm nước uống theo khoảng giá (Chạy)
    private void btntimkiemnutheogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemnutheogiaActionPerformed
        double inputTuGia = Integer.parseInt(JOptionPane.showInputDialog(this,
                "Từ"));
        double inputDenGia = Integer.parseInt(JOptionPane.showInputDialog(this,
                "Đến"));

        if (inputTuGia > 0 && inputDenGia > 0) {
            try {
                dsnu = QLNuocUong.timKiemNU(inputTuGia, inputDenGia);
                
                tableModel = (DefaultTableModel) tbnuocuong.getModel();

                tableModel.setRowCount(0);

                dsnu.forEach(nu -> {
                    tableModel.addRow(new Object[]{
                        nu.getMaSP(),
                        nu.getTenSP(),
                        nu.getGiaBan(),
                        nu.getTinhTrang(),
                        nu.getThoiDiemBan(),
                        nu.getDanhMuc(),
                        nu.getLoaiNU()
                    });
                });
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btntimkiemnutheogiaActionPerformed
    //Button sắp xếp nước uống theo giá giảm dần
    private void btnsapxepnutheogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapxepnutheogiaActionPerformed
        try {
            QLNuocUong.sapXepNuocUongTheoGia();
            showDanhSachNUSapXep();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnsapxepnutheogiaActionPerformed
    //Button chọn thức ăn (Chạy)
    private void btnchonTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonTAActionPerformed
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbthucan.getSelectedRow();
        if (selectedIndex >= 0) { //Đúng
            ThucAn ta= dsta.get(selectedIndex);
            //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
            int option = JOptionPane.showConfirmDialog(this, "Thêm Thức Ăn vào danh sách đặt thức ăn");
            System.out.println("option: " + option);  
            //Ouput => Yes: 0, No: 1, Cancel: 2
            if (option == 0) {
                try {
                    QLThucAn.chonTA(ta);
                    JOptionPane.showMessageDialog(this, "Chọn Thức Ăn thành công",
                            "Chọn Thức Ăn", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnchonTAActionPerformed
    //Button chọn nước uống (Chạy)
    private void btnchonNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonNUActionPerformed
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbnuocuong.getSelectedRow();
        if (selectedIndex >= 0) { //Đúng
            NuocUong nu = dsnu.get(selectedIndex);
            //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
            int option = JOptionPane.showConfirmDialog(this, "Thêm Nước Uống vào danh sách đặt Nước uống");
            System.out.println("option: " + option);  
            //Ouput => Yes: 0, No: 1, Cancel: 2
            if (option == 0) {
                try {
                    QLNuocUong.chonNU(nu);
                    JOptionPane.showMessageDialog(this, "Chọn Nước Uống thành công",
                            "Chọn Nước Uống", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnchonNUActionPerformed
    //Button Quay Về Màn Hình Chính
    private void btnQuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayVeActionPerformed
        new ManHinhChinh().setVisible(true); //Mở màn hình mới
        this.dispose(); //Đóng màn hình hiện tại
    }//GEN-LAST:event_btnQuayVeActionPerformed
    //Button sắp xếp thức ăn theo giá giảm dần
    private void btnsxtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsxtaActionPerformed
        try {
            QLThucAn.sapXepThucAnTheoGia();
            showDanhSachTASapXep();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_btnsxtaActionPerformed
    //Button hiển thị danh sách món ăn sau khi thực hiện Button trước
    private void btnHienThiMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiMonAnActionPerformed
        try {
            showTA();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHienThiMonAnActionPerformed
    //Button hiển thị danh sách nước uống sau khi thực hiện Button trước
    private void btnHienThiNuocUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiNuocUongActionPerformed
        try {
            showNU();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHienThiNuocUongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QuanLySanPham().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLySanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiMonAn;
    private javax.swing.JButton btnHienThiNuocUong;
    private javax.swing.JButton btnQuayVe;
    private javax.swing.JButton btnchonNU;
    private javax.swing.JButton btnchonTA;
    private javax.swing.JButton btnsapxepnutheogia;
    private javax.swing.JButton btnsxta;
    private javax.swing.JButton btnthemnu;
    private javax.swing.JButton btnthemta;
    private javax.swing.JButton btntimkiemnu;
    private javax.swing.JButton btntimkiemnutheogia;
    private javax.swing.JButton btntimkiemta;
    private javax.swing.JButton btntimkiemtatheogia;
    private javax.swing.JButton btnxoanu;
    private javax.swing.JButton btnxoata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbnuocuong;
    private javax.swing.JTable tbthucan;
    // End of variables declaration//GEN-END:variables
}
