/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLCoffeeShop;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HIEU
 */
public class QuanLyBan extends javax.swing.JFrame {
    public static int dem = 0;
    private DefaultTableModel tableModel;
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
    List<Ban> dsBan = new ArrayList<>();
//    List<ChiTietHoaDon> dsHD = new ArrayList<>();

    /**
     * Creates new form QuanLyBan
     * @throws java.sql.SQLException
     */
    public QuanLyBan() throws SQLException {
        initComponents();

        showBan();
        showBanTrong();
    }
    //Show dữ liệu bàn 
    private void showBan() throws SQLException {
        //Khởi tạo bảng hiện thị bàn
        tableModel = (DefaultTableModel) tbban.getModel();
        dsBan = QLBan.findALLBan();

        tableModel.setRowCount(0);

        dsBan.forEach(b -> {
            tableModel.addRow(new Object[]{
                b.getMaBan(),
                b.getSucChua(),
                b.getTinhTrang()
            });
        });
    }
    //Show dữ liệu bàn trống 
    private void showBanTrong() throws SQLException {
        //Khởi tạo bảng hiện thị bàn trống
        tableModel = (DefaultTableModel) tbbantrong.getModel();
        dsBan = QLBan.findBanTrong();

        tableModel.setRowCount(0);

        dsBan.forEach(b -> {
            tableModel.addRow(new Object[]{
                b.getMaBan(),
                b.getSucChua(),
                b.getTinhTrang()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnQuayVe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbban = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbbantrong = new javax.swing.JTable();
        btnxoaban = new javax.swing.JButton();
        btntimkiemban = new javax.swing.JButton();
        btnthemban = new javax.swing.JButton();
        btncapnhatban = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnHienThiDSBan = new javax.swing.JButton();
        btnHienThiDanhSachBanTrong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ ĐẶT BÀN");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnQuayVe.setBackground(new java.awt.Color(255, 255, 255));
        btnQuayVe.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnQuayVe.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\outline_logout_black_24_1.png")); // NOI18N
        btnQuayVe.setText("Màn Hình Chính");
        btnQuayVe.setBorder(null);
        btnQuayVe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayVeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\outline_task_alt_black_24.png")); // NOI18N
        jButton1.setText("Đặt Bàn");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Bàn", "Sức Chứa", "Tình Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbban);

        tbbantrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Bàn", "Sức Chứa", "Tình Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbbantrong);

        btnxoaban.setBackground(new java.awt.Color(255, 255, 255));
        btnxoaban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoaban.setText("Xóa Bàn");
        btnxoaban.setBorder(null);
        btnxoaban.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoabanActionPerformed(evt);
            }
        });

        btntimkiemban.setBackground(new java.awt.Color(255, 255, 255));
        btntimkiemban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntimkiemban.setText("Tìm Kiếm Bàn");
        btntimkiemban.setBorder(null);
        btntimkiemban.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntimkiemban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiembanActionPerformed(evt);
            }
        });

        btnthemban.setBackground(new java.awt.Color(255, 255, 255));
        btnthemban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthemban.setText("Thêm Bàn");
        btnthemban.setBorder(null);
        btnthemban.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthemban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthembanActionPerformed(evt);
            }
        });

        btncapnhatban.setBackground(new java.awt.Color(255, 255, 255));
        btncapnhatban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncapnhatban.setText("Cập Nhật Bàn");
        btncapnhatban.setBorder(null);
        btncapnhatban.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncapnhatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatbanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DANH SÁCH CÁC BÀN TRỐNG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("DANH SÁCH TẮT CẢ CÁC BÀN");

        btnHienThiDSBan.setBackground(new java.awt.Color(255, 255, 255));
        btnHienThiDSBan.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\baseline_refresh_black_18.png")); // NOI18N
        btnHienThiDSBan.setBorder(null);
        btnHienThiDSBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiDSBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiDSBanActionPerformed(evt);
            }
        });

        btnHienThiDanhSachBanTrong.setBackground(new java.awt.Color(255, 255, 255));
        btnHienThiDanhSachBanTrong.setIcon(new javax.swing.ImageIcon("C:\\Users\\HIEU\\Desktop\\OOP\\THchuong2\\BTL_QLCOFFEESHOP\\src\\main\\java\\QLCoffeeShop\\images\\baseline_refresh_black_18.png")); // NOI18N
        btnHienThiDanhSachBanTrong.setBorder(null);
        btnHienThiDanhSachBanTrong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHienThiDanhSachBanTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiDanhSachBanTrongActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("DANH SÁCH CÁC BÀN TRỐNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHienThiDanhSachBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHienThiDSBan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncapnhatban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnxoaban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthemban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntimkiemban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnHienThiDSBan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthemban, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoaban, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncapnhatban, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btntimkiemban, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHienThiDanhSachBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Button thêm bàn (chạy) <thêm thẳng vào CSDL>
    private void btnthembanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthembanActionPerformed
        try {
            int inputmaBan = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Nhập mã Bàn"));
            int inputsc = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Nhập sức chứa"));
            String inputtinhTrang = JOptionPane.showInputDialog(this, "Nhập tình trạng");
            
            //Chọn phương thức khởi tạo không ID vì ID là khóa chính của bảng
            Ban b = new Ban(inputmaBan,inputsc, inputtinhTrang);
            
            QLBan.themBan(b);
            showBan();
            showBanTrong();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnthembanActionPerformed

    private void btncapnhatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatbanActionPerformed
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbban.getSelectedRow();
        String row = tbban.getModel().getValueAt(selectedIndex, 0).toString();
        if (selectedIndex >= 0){
            try {
                int inputsc = Integer.parseInt(JOptionPane.showInputDialog(this,
                        "Nhập sức chứa"));
                String inputTinhTrang = JOptionPane.showInputDialog(this, "Nhập tình trạng");
                
                Ban b = new Ban(inputsc, inputTinhTrang);
                QLBan.capnhatBan(b, row);
                showBan();
                showBanTrong();
                
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btncapnhatbanActionPerformed
    //Button xóa bàn (Chạy)
    private void btnxoabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoabanActionPerformed
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbban.getSelectedRow();
        String row = tbban.getModel().getValueAt(selectedIndex, 0).toString();
//        if (selectedIndex >= 0) { //Đúng
//            Ban b = dsBan.get(selectedIndex);
        //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa bàn này?");
        System.out.println("option: " + option);
        //Ouput => Yes: 0, No: 1, Cancel: 2
        if (option == 0) {
            try {
                QLBan.xoaBan(row);//Xóa Bàn
                showBan(); //Hiện thị danh sách nhân viên sau khi xóa
                showBanTrong();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnxoabanActionPerformed
    //Button tìm kiếm bàn theo sức chứa (Chạy)
    private void btntimkiembanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiembanActionPerformed
        int input = Integer.parseInt(JOptionPane.showInputDialog(this,
                "Nhập sức chứa"));
        if (input > 0) {
            try {
                dsBan = QLBan.timKiemBan(input);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableModel = (DefaultTableModel) tbban.getModel();
            
            tableModel.setRowCount(0);

            dsBan.forEach(b -> {
                tableModel.addRow(new Object[]{
                    b.getMaBan(),
                    b.getSucChua(),
                    b.getTinhTrang()
                });
            });
        }
    }//GEN-LAST:event_btntimkiembanActionPerformed
    //Button Đặt Bàn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Lấy ra vị trí index khi click chuột
        int selectedIndex = tbbantrong.getSelectedRow();
        if (selectedIndex >= 0) { //Đúng
            Ban b = dsBan.get(selectedIndex);
            //Hiển thị một Pop-up Panel xác nhận xóa, sau khi nhấn Delete
            int option = JOptionPane.showConfirmDialog(this, "Thêm bàn vào Danh Sách Đặt Bàn?");
            System.out.println("option: " + option);  
            //Ouput => Yes: 0, No: 1, Cancel: 2
            if (option == 0) {
                try {
                    QLBan.datBan(b);
                    JOptionPane.showMessageDialog(this, "Đặt bàn thành công",
                            "Đặt bàn", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //Button Quay Về Màn Hình Chính
    private void btnQuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayVeActionPerformed
        new ManHinhChinh().setVisible(true); //Mở màn hình mới
        this.dispose(); //Đóng màn hình hiện tại
    }//GEN-LAST:event_btnQuayVeActionPerformed
    //Button hiển thị lại danh sách bàn sau khi đã thực hiện Button trước
    private void btnHienThiDSBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiDSBanActionPerformed
        try {
            showBan();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHienThiDSBanActionPerformed
    //Button hiển thị lại danh sách bàn trống sau khi đã thực hiện Button trước
    private void btnHienThiDanhSachBanTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiDanhSachBanTrongActionPerformed
        try {
            showBanTrong();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHienThiDanhSachBanTrongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QuanLyBan().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyBan.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiDSBan;
    private javax.swing.JButton btnHienThiDanhSachBanTrong;
    private javax.swing.JButton btnQuayVe;
    private javax.swing.JButton btncapnhatban;
    private javax.swing.JButton btnthemban;
    private javax.swing.JButton btntimkiemban;
    private javax.swing.JButton btnxoaban;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tbban;
    private javax.swing.JTable tbbantrong;
    // End of variables declaration//GEN-END:variables
}
